env:
  env_name: sim_valve
  verbose: true
  model_file: dclaw3xh_valve3_default.xml
  env_color: rgb_valve
  inplicit_step: 200
  ctrl_interpolation_margin_step: 40
  viewer:
    is_Offscreen: false
  target:
    visible: false
  render:
    camera_name_list:
    - random_nonfix
    - canonical
    width_capture: 64
    height_capture: 64
  texture:
    randomization_mode: per_step
    is_dynamc_noise: false
    task_relevant_geom_group_name: valve
  joint_range:
    robot:
      lower_bound:
      - -0.3491
      - -0.5236
      - -1.0e-06
      upper_bound:
      - 0.7854
      - 0.5236
      - 1.0e-06
    object:
      lower_bound: -12.566370614359172
      upper_bound: 12.566370614359172
  init_state:
    task_space_position:
    - 0.65
    - 0.18
    - 0.65
    robot_velocity:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    object_position:
    - 0.0
    object_velocity:
    - 0.0
    time: 0.0
    act: null
    udd_state: {}
  dynamics:
    robot:
      kp_claw: 20.0
      damping_claw: 0.1625
      frictionloss_claw: 0.05
    object:
      kp_valve: 0.0
      kv_valve: 0.0
      damping_valve: 0.2
      frictionloss_valve: 0.3
  camera:
    x_coordinate: 0.0
    y_coordinate: 0.0
    z_distance: 0.325
    orientation: 0.0
  light:
    light1: 0
    light2: 16
icem:
  num_cem_iter: 7
  planning_horizon: 10
  dim_action: 3
  dimension_of_interst:
  - 0
  - 1
  - 2
  colored_noise_exponent:
  - 0.5
  - 1.0
  - 2.0
  - 3.0
  - 4.0
  lower_bound_sampling: -0.2
  upper_bound_sampling: 0.2
  lower_bound_simulated_path: -1.0
  upper_bound_simulated_path: 8.0
  dim_path: 1
  num_sample: 600
  decay_sample: 1.25
  num_subparticle: 20
  std_subparticle: 0.025
  num_elite: 1
  fraction_rate_elite: 1.0
  alpha: 0.5
  init_std: 0.75
  figsize_path:
  - 4
  - 4
  figsize_cost:
  - 4
  - 4
  debug: false
  verbose: true
  verbose_additional: false
  save_visualization_dir: ./fig
  is_verbose_newline: true
run:
  step: 25
  sequence: 50
save_dir: /nfs/workspace/robel_dclaw_env/saved_data_icem/[num_sample=600]-[num_subparticle=20]-[num_cem_iter=7]-[colored_noise_exponent=[0.5,
  1.0, 2.0, 3.0, 4.0]]-1682103006.6260257
